dpo:
  max_num_epochs: 1
  max_num_steps: 20000
  val_period: 50
  val_batches: 4
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: false
  seed: 42

  reference_policy_kl_penalty: 5
  preference_average_log_probs: true
  sft_average_log_probs: ${.preference_average_log_probs}
  preference_loss_weight: 1
  sft_loss_weight: 0.01

checkpointing:
  enabled: true
  checkpoint_dir: "/mnt/data/pmartins/nemo_rl_ckpts/dpo_mind_qwen30ba3b_merged_thinking_experts-0210-40-gold-2410-50"
  metric_name: "val_loss"
  higher_is_better: false
  keep_top_k: 3
  save_period: 78
  checkpoint_must_save_by: null

policy:
  model_name: swordhealth/qwen3-30B-A3B-merged-thinking_experts-0210-Thinking-2507-012012012012040012
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 32
  train_micro_batch_size: 1
  max_total_sequence_length: 16384
  precision: "bfloat16"
  dtensor_cfg:
    enabled: false

  dynamic_batching:
    enabled: false

  sequence_packing:
    enabled: false

  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  max_grad_norm: 1.0

  optimizer: null

  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    activation_checkpointing: true
    tensor_model_parallel_size: 2
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 8
    pipeline_model_parallel_size: 1
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    sequence_parallel: true
    freeze_moe_router: false
    moe_router_dtype: "fp64"
    moe_router_load_balancing_type: "aux_loss"
    moe_router_bias_update_rate: 1e-3
    moe_permute_fusion: false
    apply_rope_fusion: True
    
    optimizer:
      optimizer: "adam"
      lr: 5.0e-7
      min_lr: 5.0e-7
      weight_decay: 0.1
      bf16: true
      fp16: false
      params_dtype: "float32"

      #adam
      adam_beta1: 0.9
      adam_beta2: 0.98
      adam_eps: 1e-8

      #sgd
      sgd_momentum: 0.9

      #distributed optimizer
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true

      clip_grad: ${policy.max_grad_norm}

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "constant"
      lr_decay_iters: 78
      lr_warmup_iters: 7
      lr_warmup_init: 0

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      data_parallel_sharding_strategy: "optim_grads_params"

data:
  dataset_name: /mnt/data/pmartins/data/merged_datasets/DPO-chat-gold-safety-2410-50/
  data_cls: mind
  max_input_seq_length: ${policy.max_total_sequence_length}
  shuffle: true
  num_workers: 1

logger:
  log_dir: "dpo_logs/dpo_mind_qwen30ba3b_merged_thinking_experts_gold_2410-50"
  wandb_enabled: false
  tensorboard_enabled: true
  mlflow_enabled: false
  swanlab_enabled: false
  monitor_gpus: true
  wandb:
    project: nemo-rl
    name: dpo_mind_qwen30ba3b_merged_thinking_experts_gold_2410-50
  tensorboard:
    log_dir: dpo_mind_qwen30ba3b_merged_thinking_experts_gold_2410-50
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10

cluster:
  gpus_per_node: 8
  num_nodes: 1
