defaults: ../../grpo_math_1B.yaml

grpo:
  num_prompts_per_step: 64
  num_generations_per_prompt: 8
  max_num_epochs: 1
  max_num_steps: 82
  normalize_rewards: true
  use_leave_one_out_baseline: true
  val_period: 10
  val_at_start: false
  max_val_samples: 256
  val_batch_size: 256
  async_grpo:
    enabled: false
    max_trajectory_age_steps: 1

loss_fn:
  reference_policy_kl_penalty: 0.01
  ratio_clip_min: 0.2
  ratio_clip_max: 0.28
  use_on_policy_kl_approximation: true
  use_importance_sampling_correction: false
  token_level_loss: true
  ratio_clip_c: null

checkpointing:
  enabled: false
  checkpoint_dir: results_grpo/grpo-qwen4b-mind-verifiable
  metric_name: "val:val_reward"
  higher_is_better: true
  keep_top_k: 3
  save_period: 82
  checkpoint_must_save_by: null

policy:
  model_name: /mnt/data/shared/models/Qwen3-4B-Thinking-2507/
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 512
  train_micro_batch_size: 1
  generation_batch_size: 64
  logprob_batch_size: 8
  max_total_sequence_length: 8192
  precision: "bfloat16"

  dtensor_cfg:
    enabled: false

  dynamic_batching:
    enabled: False
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    logprob_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.logprob_batch_size}}
    sequence_length_round: 64

  sequence_packing:
    enabled: false
    algorithm: modified_ffd
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    logprob_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.logprob_batch_size}}
    sequence_length_round: 64

  max_grad_norm: 1.0
  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}

  optimizer: null
  scheduler: null
  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    activation_checkpointing: false
    converter_type: "LlamaForCausalLM"
    tensor_model_parallel_size: 1
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    sequence_parallel: false
    freeze_moe_router: true
    moe_router_dtype: "fp64"
    moe_router_load_balancing_type: "none"
    moe_router_bias_update_rate: 0.0
    moe_permute_fusion: false
    apply_rope_fusion: True

    optimizer:
      optimizer: "adam"
      lr: 3.0e-07
      min_lr: 3.0e-08
      weight_decay: 0.01
      bf16: true
      fp16: false
      params_dtype: "float32"
      adam_beta1: 0.9
      adam_beta2: 0.999
      adam_eps: 1e-8
      sgd_momentum: 0.9
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true
      clip_grad: ${policy.max_grad_norm}

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "constant"
      lr_decay_iters: 1000
      lr_warmup_iters: 50
      lr_warmup_init: 3.0e-08

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      use_custom_fsdp: false
      data_parallel_sharding_strategy: "optim_grads_params"

    env_vars:
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:False
  generation:
    backend: "vllm"
    max_new_tokens: ${policy.max_total_sequence_length}
    temperature: 1.0
    top_p: 1.0
    top_k: null
    vllm_cfg:
      tensor_parallel_size: 4
      gpu_memory_utilization: 0.7
      max_model_len: ${policy.max_total_sequence_length}
    colocated:
      enabled: true
      resources:
        gpus_per_node: null
        num_nodes: null

env:
  mind_verifiable:
    enabled: true
    stop_strings: null

data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  prompt_file: null
  system_prompt_file: null
  shuffle: true
  dataset_name: /mnt/data/pmartins/data/rlvr/Dolci-Think-RL-if
  data_cls: "mind"

logger:
  log_dir: logs_grpo/grpo-qwen4b-mind-verifiable
  num_val_samples_to_print: 0
  wandb_enabled: false
  tensorboard_enabled: true
  mlflow_enabled: false
  swanlab_enabled: false
  monitor_gpus: false
  wandb:
    project: nemo-rl
    name: grpo-qwen4b-mind-verifiable
  tensorboard: {}
  mlflow:
    experiment_name: "nemo-rl"
    run_name: "grpo-qwen4b-mind-verifiable"
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10

cluster:
  gpus_per_node: 8
  num_nodes: 1