defaults:
  - sft.yaml

sft:
  max_num_epochs: 1
  max_num_steps: 1000000
  val_period: 100
  val_batches: 8
  val_global_batch_size: 32
  val_micro_batch_size: 1
  val_at_start: false
  seed: 42

checkpointing:
  enabled: true
  checkpoint_dir: "results/sft_vlm_megatron_${policy.model_name}__"
  metric_name: "val:val_loss"
  higher_is_better: false
  keep_top_k: 3
  save_period: 100
  checkpoint_must_save_by: null

policy:
  model_name: "Qwen/Qwen3-VL-4B-Instruct"
  tokenizer:
    name: ${policy.model_name}
  train_global_batch_size: 16
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  precision: "bfloat16"

  offload_optimizer_for_logprob: false

  dtensor_cfg:
    enabled: false

  dynamic_batching:
    enabled: false

  sequence_packing:
    enabled: false
    train_mb_tokens: ${mul:${policy.max_total_sequence_length}, ${policy.train_micro_batch_size}}
    algorithm: "modified_first_fit_decreasing"
    sequence_length_round: 64

  make_sequence_length_divisible_by: ${policy.megatron_cfg.tensor_model_parallel_size}
  max_grad_norm: 1.0
  optimizer: null
  scheduler: null

  megatron_cfg:
    enabled: true
    empty_unused_memory_level: 1
    activation_checkpointing: false
    converter_type: "Qwen2ForCausalLM"
    tensor_model_parallel_size: 1
    expert_tensor_parallel_size: 1
    expert_model_parallel_size: 1
    pipeline_model_parallel_size: 1
    sequence_parallel: false
    context_parallel_size: 1
    pipeline_dtype: ${policy.precision}
    num_layers_in_first_pipeline_stage: null
    num_layers_in_last_pipeline_stage: null
    freeze_moe_router: true
    moe_router_dtype: "fp64"
    moe_router_load_balancing_type: "none"
    moe_router_bias_update_rate: 0.0
    moe_permute_fusion: false
    moe_token_dispatcher_type: "allgather"
    moe_grouped_gemm: true
    moe_per_layer_logging: false
    apply_rope_fusion: true
    bias_activation_fusion: true
    defer_fp32_logits: false

    optimizer:
      optimizer: "adam"
      lr: 1e-5
      min_lr: 1e-6
      weight_decay: 0.01
      bf16: true
      fp16: false
      params_dtype: "float32"
      adam_beta1: 0.9
      adam_beta2: 0.999
      adam_eps: 1e-8
      sgd_momentum: 0.9
      use_distributed_optimizer: true
      use_precision_aware_optimizer: true
      clip_grad: ${policy.max_grad_norm}
      optimizer_cpu_offload: false
      optimizer_offload_fraction: 0.0

    scheduler:
      start_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      end_weight_decay: ${policy.megatron_cfg.optimizer.weight_decay}
      weight_decay_incr_style: "constant"
      lr_decay_style: "cosine"
      lr_decay_iters: 1000
      lr_warmup_iters: 50
      lr_warmup_init: 1e-7

    distributed_data_parallel_config:
      grad_reduce_in_fp32: false
      overlap_grad_reduce: true
      overlap_param_gather: true
      average_in_collective: true
      use_custom_fsdp: false
      data_parallel_sharding_strategy: "optim_grads_params"

    env_vars:
      PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:False"

data:
  max_input_seq_length: ${policy.max_total_sequence_length}
  dataset_name: "mmoukouba/MedPix-VQA"
  data_cls: "medpix_vqa"
  prompt_file: null
  split: "trainA"
  add_bos: true
  add_eos: true
  add_generation_prompt: false
  shuffle: true
  num_workers: 8
  seed: 42

logger:
  log_dir: "logs/sft_vlm_megatron_3B"
  wandb_enabled: false
  tensorboard_enabled: true
  mlflow_enabled: false
  swanlab_enabled: false
  monitor_gpus: true
  num_val_samples_to_print: 0
  wandb:
    project: "nemo-rl"
    name: "sft-vlm-megatron-3B"
  tensorboard:
    log_dir: "tb_logs-sft-vlm-megatron-3B"
  mlflow:
    experiment_name: "nemo-rl"
    run_name: "sft-vlm-megatron-3B"
  gpu_monitoring:
    collection_interval: 10
    flush_interval: 10

cluster:
  gpus_per_node: 8
  num_nodes: 1
